export const hostel = [
  {
    id: 1,
    name: "Arafims Hostel",
    lga: "Oke-Odo",
    state: "Kwara State",
    price: "#100,000 / year",
    address: "20, somewhere on earth street",
    occupants: "2 in a room",
    details: [
      "1 room with beds",
      "2 people in a room",
      "Kitchen",
      "Toilet and Bathroom",
      "Large Wardrobe",
      "Air Conditioner",
    ],
  },

  {
    id: 2,
    name: "Arafims Hostel",
    lga: "Oke-Odo",
    state: "Kwara State",
    price: "#100,000 / year",
    address: "20, somewhere on earth street",
    occupants: "2 in a room",
    details: [
      "1 room with beds",
      "2 people in a room",
      "Kitchen",
      "Toilet and Bathroom",
      "Large Wardrobe",
      "Air Conditioner",
    ],
  },

  {
    id: 3,
    name: "Arafims Hostel",
    lga: "Oke-Odo",
    state: "Kwara State",
    price: "#100,000 / year",
    address: "20, somewhere on earth street",
    occupants: "2 in a room",
    details: [
      "1 room with beds",
      "2 people in a room",
      "Kitchen",
      "Toilet and Bathroom",
      "Large Wardrobe",
      "Air Conditioner",
    ],
  },
];
