export const hostel = [
  {
    id: 1,
    name: "Arafims Hostel",
    lga: "Oke-Odo",
    state: "Kwara State",
    price: "#100,000 / year",
    address: "20, somewhere on earth street",
    occupants: "2 / room",
    details: [
      "1 room with beds",
      "2 people in a room",
      "Kitchen",
      "Toilet and Bathroom",
      "Large Wardrobe",
      "Air Conditioner",
    ],
  },

  {
    id: 2,
    name: "Adeleke Hostel",
    lga: "Ikeja",
    state: "Lagos State",
    price: "#250,000 / year",
    address: "20, somewhere on earth street",
    occupants: "1 / room",
    details: [
      "Bed",
      "Stable Electricity",
      "Kitchen",
      "Toilet and Bathroom",
      "Large Wardrobe",
      "Air Conditioner",
    ],
  },

  {
    id: 3,
    name: "Oremi Hostel",
    lga: "Ota",
    state: "Ogun State",
    price: "#80,000 / year",
    address: "20, somewhere on earth street",
    occupants: "2 / room",
    details: [
      "1 room with beds",
      "2 people in a room",
      "Kitchen",
      "Toilet and Bathroom",
      "Large Wardrobe",
      "Air Conditioner",
    ],
  },
];
